"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['typster.py']
DATA_FILES = ['c_words.txt']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'logoapp.icns'
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
